

== Implementations

Various related implementations already exist.

=== SOFP WFS3 Weather Server

Finnish Meteorological Institute (FMI), Vaisala and Spatineo have developed a Proof-of-Concept OGC Core - Features (WFS3) server. The main goals of the project are to experiment feasibility of WFS3 in providing weather observations and forecasts and a new _O&M Simple Feature Encodings_-data model (OMFS).

Used encoding of OMFS data model is based on GeoJSON. It is designed to ease the use of environmental data in web-based applications without still keeping a required (minimal) level of metadata and semantics. The data model enables data sharing and processing with a variety of existing technologies having simple feature handling capabilities. The data model is one alternative to consider in _Maintenance and Implementation Work Programme 2016-2020, Action 2017.2 on alternative encodings for INSPIRE data_.

The API has been tested in several ways. One implementation is available in FMI Open Data portal with selected data sets. Feedback is also gathered in _INSPIRE Helsinki 2019_ event where project partners have a challenge _Commuting 2.0_ to boost environmentally-friendly commuting. Both FMI and Vaisala have open implementations available during the challenge.

The server is implemented with NodeJS and TypeScript. The server architecture is modular: the core takes care of API and data encoding while different data-store integrations extract and process requested information from the underlying data sources such as files, databases or other services.

[%header,cols=2*]
|===
|Content
|Link

|Server core source code
|https://github.com/vaisala-oss/sofp-core

|FMI data integration source code
|https://github.com/fmidev/smartmet-sofp-backend

|OMSF profile repository
|https://github.com/opengeospatial/omsf-profile
