

== Implementations

Various related implementations already exist.

=== SOFP WFS3 Weather Server

Finnish Meteorological Institute (FMI), Vaisala and Spatineo have developed a Proof-of-Concept OGC Core - Features (WFS3) server. The main goals of the project are to experiment feasibility of WFS3 in providing weather observations and forecasts and a new _O&M Simple Feature Encodings_-data model (OMFS).

Used encoding of OMFS data model is based on GeoJSON. It is designed to ease the use of environmental data in web-based applications without still keeping a required (minimal) level of metadata and semantics. The data model enables data sharing and processing with a variety of existing technologies having simple feature handling capabilities. The data model is one alternative to consider in _Maintenance and Implementation Work Programme 2016-2020, Action 2017.2 on alternative encodings for INSPIRE data_.

The API has been tested in several ways. One implementation is available in FMI Open Data portal with selected data sets. Feedback is also gathered in _INSPIRE Helsinki 2019_ event where project partners have a challenge _Commuting 2.0_ to boost environmentally-friendly commuting. Both FMI and Vaisala have open implementations available during the challenge.

The server is implemented with NodeJS and TypeScript. The server architecture is modular: the core takes care of API and data encoding while different data-store integrations extract and process requested information from the underlying data sources such as files, databases or other services.

[%header,cols=2*]
|===
|Content
|Link

|Server core source code
|https://github.com/vaisala-oss/sofp-core

|FMI data integration source code
|https://github.com/fmidev/smartmet-sofp-backend

|OMSF profile repository
|https://github.com/opengeospatial/omsf-profile
|===

=== Meteorological Service of Canada GeoMet OGC API

In support of the https://canada.ca/climate-services[Canadian Centre for Climate Services] (CCCS), the Meteorological Service of Canada (MSC), as part of their https://www.canada.ca/en/environment-climate-change/services/weather-general-tools-resources/weather-tools-specialized-data/geospatial-web-services.html[GeoMet] platform, deployed an initial offering of weather, climate and water data via the OGC API - Features standard.  Made available in 2018, initial datasets included historical hydrometric and climate data.

Data was encoded as GeoJSON and was also provided via HTML representation.  The API was used as part of the CCCS https://climate-change.canada.ca/climate-data/[Climate data extraction tool], allowing users to visualize and access/download archive data with spatial, aspatial and temporal criteria for just in time data extraction of data relevant to their use case.  Future phases of the API will include real time weather observations and hydrometric data.  The API is also used for climate data extraction via the recently launched collaborative portal at https://climatedata.ca[ClimateData.ca].

The server is implemented with in Python with https://pygeoapi.io[pygeoapi] and provides a robust plugin architecture for extensibility.  Supported backends include Elasticsearch, PostgreSQL/PostGIS and GeoPackage.

[%header,cols=2*]
|===
|Content
|Link

|OGC API - Feature endpoint
|https://geo.weather.gc.ca/geomet/features

|Source code
|https://github.com/geopython/pygeoapi

|Website
|https://pygeoapi.io
|===


