

== Hackathons/Workshops
=== December 2018 Workshop/Hackathon in Northern Virginia
==== Background
In December 2018, the MetOean DWG conducted a two day API workshop/hackathon event in Northern Virginia.  The goal of the workshop was to introduce the weather on the web data API work as a REST-based query pattern making use of the OpenAPI specification and discuss how the API tries to simplify the need to understand the OGC WCS standard or the need to know about Meteorological or Oceanographic terms.  That the API was simply a quick means to an end goal, the product.   Discussion topics included the URL request/response patterns, the query patterns, and user experiences making use of the demo APO.   The full agenda for the workshop/hackathon can be found [[here]].  Participants of the workshop included OGC staff, a number of Met Center Agencies, academia, and corporations. A complete listing of the participants can be found [[here]].

==== What was achieved

1.	Created a GitHub collaborative workspace environment for MetOcean API:   https://github.com/OGCMetOceanDWG/MetOceanAPI-Workshop 

2.	Demonstration of initial WotW capability, focused on gridded data

3.	OpenAPI demo endpoint independent testing (Canadian Centre for Meteorological and Environmental Prediction)
 
 a.	Successfully conducted first pass testing against a generic WFS 3.0 client library (OWSLib - https://github.com/geopython/OWSLib)
 
 b.	Provided recommendations to align closer to WFS 3.0 patterns in GitHub: https://github.com/OGCMetOceanDWG/MetOceanAPI-Workshop/blob/master/api-review-comments.md

4.	Initial cut at WOTW API conformance classes (See Conformance Class file)
 
 4.1	Core (0):  Use simple feature specification (point, line string, polygon).  How do we interpret this in terms of parameters?  How do we encode this?  Start value, end value, interval, Begin, end, enumeration.  This would be same for time and points.  CRS is fixed on 4326.  Parameter list would be a list of WMO vocabulary (Links to 2 Grib tables)
 
 4.2	Spatial (1):  required for start, stop, interval and enumeration.  Not required for start and stop.  Specify default for interpolation, vertical, time.  For cross section and corridors use line string terminology (harder case though).  
 
 4.3	Weather parameters (2): Use WFS as the basis for query parameters.  Create filter.  The API should be self describing and therefore advertise what parameters are available.  There will likely be restrictions to output encodes for Grib vs. json.
 
 4.4	Temporal (3);  Use MetOcean specification, Grib2, netCDF
 
 4.5	Measurements (4): 
 
 4.6	Interpolation (5): Must specify interpolation method per axis.  Must use well known method.  Specify default as nearest neighbor.  Work on other interpolations methods with vendors 
 
 4.7	Return(6): We inform.  Json, covjson, grib, netcdf, xml 
 
 4.8	Vendor Extras (7):  Outside of scope.

5.  Initial cut at supported MetOcean API geometry query types (See: query pattern mappings file)
 
 5.1	Point, point series
 
 5.2	Polygon
 
 5.3 Profile
 
 5.4	grid
 
 5.5	Corridor
 
 5.6	Trajectory

== Implementations

Various related implementations already exist.

=== SOFP WFS3 Weather Server

Finnish Meteorological Institute (FMI), Vaisala and Spatineo have developed a Proof-of-Concept OGC Core - Features (WFS3) server. The main goals of the project are to experiment feasibility of WFS3 in providing weather observations and forecasts and a new _O&M Simple Feature Encodings_-data model (OMFS).

Used encoding of OMFS data model is based on GeoJSON. It is designed to ease the use of environmental data in web-based applications without still keeping a required (minimal) level of metadata and semantics. The data model enables data sharing and processing with a variety of existing technologies having simple feature handling capabilities. The data model is one alternative to consider in _Maintenance and Implementation Work Programme 2016-2020, Action 2017.2 on alternative encodings for INSPIRE data_.

The API has been tested in several ways. One implementation is available in FMI Open Data portal with selected data sets. Feedback is also gathered in _INSPIRE Helsinki 2019_ event where project partners have a challenge _Commuting 2.0_ to boost environmentally-friendly commuting. Both FMI and Vaisala have open implementations available during the challenge.

The server is implemented with NodeJS and TypeScript. The server architecture is modular: the core takes care of API and data encoding while different data-store integrations extract and process requested information from the underlying data sources such as files, databases or other services.

[%header,cols=2*]
|===
|Content
|Link

|Server core source code
|https://github.com/vaisala-oss/sofp-core

|FMI data integration source code
|https://github.com/fmidev/smartmet-sofp-backend

|OMSF profile repository
|https://github.com/opengeospatial/omsf-profile
|===

=== Meteorological Service of Canada GeoMet OGC API

In support of the https://canada.ca/climate-services[Canadian Centre for Climate Services] (CCCS), the Meteorological Service of Canada (MSC), as part of their https://www.canada.ca/en/environment-climate-change/services/weather-general-tools-resources/weather-tools-specialized-data/geospatial-web-services.html[GeoMet] platform, deployed an initial offering of weather, climate and water data via the OGC API - Features standard.  Made available in 2018, initial datasets included historical hydrometric and climate data.

Data was encoded as GeoJSON and was also provided via HTML representation.  The API was used as part of the CCCS https://climate-change.canada.ca/climate-data/[Climate data extraction tool], allowing users to visualize and access/download archive data with spatial, aspatial and temporal criteria for just in time data extraction of data relevant to their use case.  Future phases of the API will include real time weather observations and hydrometric data.  The API is also used for climate data extraction via the recently launched collaborative portal at https://climatedata.ca[ClimateData.ca].

The server is implemented with in Python with https://pygeoapi.io[pygeoapi] and provides a robust plugin architecture for extensibility.  Supported backends include Elasticsearch, PostgreSQL/PostGIS and GeoPackage.

[%header,cols=2*]
|===
|Content
|Link

|OGC API - Feature endpoint
|https://geo.weather.gc.ca/geomet/features

|Source code
|https://github.com/geopython/pygeoapi

|Website
|https://pygeoapi.io
|===


