

== API Interoperability

=== SOFP WFS3 Weather Server

To gain maximal interoperability, the defined API should be as general as possible. The general parts empower existing libraries and software to communicate with the API. Excessively general design, however, present unnecessary confusion since the API is not intuitive and/or it works inconsistently.

_SOFP WFS3 Weather Server_ were build to fully meet _OGC API - Features Core_ to gain maximal client support and easy access to the data to developers outside the geospatial community. Following challenges and shortcomings in the current standard were identified.

==== Simple Observation Time Series

To request all temperature and humidity observations from a time range inside the given area, the following request could be used:

 GET /datasets/weather/observation/aws/items?
   parametername=Temperature,Humidity
   &time=20181204T150000/20181204T180000
   &bbox=20,60,30,70

The request is _OGC API - Features Core_ compatible except the time definition, which would need an extension. Time range support is widely adopted in a broad range of applications and would be reasonable to define in _OGC API - Features_ standard. However, other time definitions used in many environmental domains such as origin time and lead time are not commonly recognised and would require a domain-specific specification.

==== Resampled Weather Forecast Model Output

To request a weather model output inside some area, following request could be used:

 GET /datasets/weather/forecast/harmonie/items?
   parametername=Temperature,Humidity
   &time=20181204T150000/20181204T180000
   &bbox=20,60,30,70
   &limit=100

The request returns a collection of features containing a resampled regular grid with 100 points (10x10) inside the given bounding box. All features are resampled and generated on-demand based on the request. Smaller bounding box would return more detailed information and a larger one less detailed. The pattern is fully compatible with _OGC API - Features Core_ but may be unintuitive to the users used to handle pre-existing features.

==== Single Point Weather Forecast Model Output

_SOFP WFS3 Weather Server_ allows users to request any single point as well. In those cases, it interpolates the response on-demand to the exact requested location in space and time. The functionality is achieved with a (mis)usage of standard filtering defined in _OGC API - Features Core_:

 GET /datasets/weather/forecast/harmonie/items?
   parametername=Temperature,Humidity
   &time=20181204T150000/20181204T180000
   &bbox=20,60,30,70
   &lat=60.159900&lon=24.876116

The pattern is fully Core-compatible but clients are allowed to request _any_ latitude and longitude inside the data area. The upside of such behaviour is wide client support and the downside is possible obscurity. The functionality can, of course, be described to the developers in OpenAPI definition and API can be extended with query parameters such as _interpolation_method_, but the main concern of the balance between interpretability and clarity remains.

== Data Format

=== OGC Observations and Measurements - Simple Feature model & encodings (OMSF)

TBD

== Other Notes

=== Feature IDs

_OGC API - Features_ standard assumes that all features have a unique identifier, which may be problematic if responses are generated on-demand (for example in _SOFP WFS3 Weather Server_). In case of weather forecasts, IDs can be formed in a unique manner on-demand following:

 parameter:producer:level_type:level:forecast_type:ensemble_number:origin_time:area:time:area_interpolation_method:time_interpolation_method:level_interpolation_method

This convention makes the feature ID to a query language itself, which may be beneficial for power users.

=== Forming Collections

_OGC API - Features_ leaves relatively lot degree of freedom to form collections in different ways. To serve a wide range of domains, this is naturally necessary. In a more specific domain, such as serving weather data, different conventions may be confusing to the end-users. It would be advisable to harmonise at least the following aspects:

- One collection per weather model or one collection per parameter?
- One entry point per organisation or on entry point per dataset (i.e. weather model) or one entry point per data type (i.e. observations/forecast/climatology)?

== Meteorological Service of Canada GeoMet OGC API

The OGC API - Features Core specification provides a valuable developer experience and lowers the barrier to interacting with geosaptial data.  Below are some considerations for further research and collaboration.

=== Hierarchy

The current MSC OGC API offering provides a flat list of collections.  Community input and consensus will provide value into better organizing and categorizing collection trees which will help with user navigation of the API.

=== Complex Filtering

By design, the OGC API - Features Core specification provides query capability via spatial, aspatial and temporal predicates.  More complex query capabilities (spatial operators [clip by polygon, etc.], comparisons [greater than, less than, etc.], as well as logical operators [And/Or/Not, etc.]) are required for more complex use cases.  This is best implemented as an extension that a given server can implement/conform to.

== Met Office candidiate specification

The candidate specification focuses on delivering a set of predefined queries, whose structure is based around the feature a user is trying to generate rather than how the data is stored.  The existing OGC standards are based on providing rich query capabilities to extract the information that the user requires from a datastore,  this is very powerful and can often allow user a similar level of access as they would have if the data was on their own system but requires both an understanding of the datastore and the various OGC standards used by the query.  

The candidate specification relies on the data publisher to provide the query patterns which return their information as just a simplified array of data with a set of metadata which describe the meaning of the values, rather than using specialised data schemas to describe the data.  This will mean there will be a loss of some specialised data capabilities but at the benefit of making it much easier for data users to 'mash' information from multiple data sources to produce their data product.

With a view to aligning with the existing OGC standards the intention is that the candidate specification will return its metadata with the same schema up to at least the level of collections as the WFS 3 api in order to make service discovery easier.  

i.e. 

http://www.example.org/wfs/collections

http://www.example.org/wotw/collections

should be parsable by the same code as the format of the returned data would be identical, but the structure of the metadata would diverge after that point.

Other benefits to the query pattern approach are:

Simplify interoperability by limiting the number of possible query combinations and results that are available for any particular API (this is usually handled by defining profiles with exiting standards).  

The limited functionality of each individual query pattern should make it easier for vendors to implement, although they still have to handle to complexity of the data the query business logic can be much simpler.  They are able to choose which patterns they want to implement and still provide a compliant interface.   

It should be easier to tune the cost/performance balance than the rich API's, limiting the functionality available via each query pattern mean  indexing, caching and other techniques for optimising performance or reducing cost are easier to structure. 

=== Metadata

For the candidate specification to work it will require a well structured approach to metadata that will be flexible enough to cope with both Feature and Coverage data types whilst not over complicating the returned results and not swamping the data response with metadata values.  The approach taken by CoverageJSON is to use JSON-LD and rely on registries to provide the detailed information, this linked data approach would keep the size of the metadata in the results to a minimum whilst providing the user access to as much (or as little) detail as the user requires to build a product.  It is not currently the intention to try an standardise the structure of the information that is stored in the registries, the concept being that information would be available for products using the data to access but it would require customisation of the product if it needs to interpret the richer detail that they provide dynamically,  this is working on a 80/20 principle that the majority of time the basic metadata available with the returned data would be good enough for most applications.

This does create the need to develop a set of registries to host the detailed metadata, this could be done by each data publisher creating their own register to describe their data and for specialist types this will always be required.  It would be much more efficient for standard things such as units if there were centrally hosted common registries that could be used by all API's and registries to host domain specific information (such as Met Ocean code tables) but this would require identify owners to host the services and manage the information.

=== CoverageJSON

The candidate specification uses CoverageJSON as its default output, this JSON format is straightforward enough that it is not intimidating to users outside of the geospatial domain but has a rich enough structure to be able to describe data and metadata from both Coverage and Feature sources.  CoverageJSON is not currently owned or managed by any standards body and although implemented in tools such as the Hyrax OpenDAP server it is a relatively unknown format,  ideally CoverageJSON would be adopted and developed by the OGC to become a formal JSON schema for geospatial data.  Whilst there are improvements that could be made to improve the CoverageJSON structure it is essential that it keeps the right balance between the very open structure of GeoJSON and the very formal structure of the current GML based schemas of the existing OGC standards.

The best approach where the API supports users who require schema validation would be for the API to provide a GML based results as one of the output format options rather than trying to extend the attributes of the CoverageJSON format which could be disconcerting to the wider audience.  This follows the principle behind the candidate specification is that it is the data publishers who convert the data into a simple format not the data consumer.